import { poseAnimation } from './PoseAnimation';
import { shurgAnimation } from './ShrugAnimation';
import { thumbsUpAnimation } from './ThumbsUpAnimation';
import { thumbsDownAnimation } from './ThumbsDownAnimation';
import { flyingUpAnimation } from './FlyingUpAnimation';
import { flyingSideAnimation } from './FlyingSideAnimation';
import { touchdownAnimation } from './TouchdownAnimation';

export const animationJsons = [
  {
    id: 0,
    name: 'pose',
    layers: {
      baseBody: { variations: [
        { id: "#F7D0B1", jsons: [
          { id: 0, json: poseAnimation.makeup.H_F7D0B1, zIndex: 2},
          { id: 1, json: poseAnimation.ears.H_F7D0B1, zIndex: 1 },
          { id: 2, json: poseAnimation.mouth.H_F7D0B1, zIndex: 2},
          { id: 3, json: poseAnimation.baseBody.H_F7D0B1, zIndex: 1},
        ]},
        { id: "#E9B58F", jsons: [
          { id: 0, json: poseAnimation.makeup.H_E9B58F, zIndex: 2},
          { id: 1, json: poseAnimation.ears.H_E9B58F, zIndex: 1 },
          { id: 2, json: poseAnimation.mouth.H_E9B58F, zIndex: 2},
          { id: 3, json: poseAnimation.baseBody.H_E9B58F, zIndex: 1},
        ]},
        { id: "#D19F7C", jsons: [
          { id: 0, json: poseAnimation.makeup.H_D19F7C, zIndex: 2},
          { id: 1, json: poseAnimation.ears.H_D19F7C, zIndex: 1 },
          { id: 2, json: poseAnimation.mouth.H_D19F7C, zIndex: 2},
          { id: 3, json: poseAnimation.baseBody.H_D19F7C, zIndex: 1},
        ]},
        { id: "#BB7751", jsons: [
          { id: 0, json: poseAnimation.makeup.H_BB7751, zIndex: 2},
          { id: 1, json: poseAnimation.ears.H_BB7751, zIndex: 1 },
          { id: 2, json: poseAnimation.mouth.H_BB7751, zIndex: 2},
          { id: 3, json: poseAnimation.baseBody.H_BB7751, zIndex: 1},
        ]},
        { id: "#A65F2C", jsons: [
          { id: 0, json: poseAnimation.makeup.H_A65F2C, zIndex: 2},
          { id: 1, json: poseAnimation.ears.H_A65F2C, zIndex: 1 },
          { id: 2, json: poseAnimation.mouth.H_A65F2C, zIndex: 2},
          { id: 3, json: poseAnimation.baseBody.H_A65F2C, zIndex: 1},
        ]},
        { id: "#3B1F1B", jsons: [
          { id: 0, json: poseAnimation.makeup.H_3B1F1B, zIndex: 2},
          { id: 1, json: poseAnimation.ears.H_3B1F1B, zIndex: 1},
          { id: 2, json: poseAnimation.mouth.H_3B1F1B, zIndex: 2},
          { id: 3, json: poseAnimation.baseBody.H_3B1F1B, zIndex: 1},
        ]},
      ]},
      hair1: { jsons: [ 
        { id: 0, colorIndex: 1, json: poseAnimation.hair1.blonde, zIndex: 0 },
        { id: 1, colorIndex: 1, json: poseAnimation.bangs1.blonde, zIndex: 3 },
        { id: 2, colorIndex: 2, json: poseAnimation.hair1.brown, zIndex: 0 },
        { id: 3, colorIndex: 2, json: poseAnimation.bangs1.brown, zIndex: 3 },
        { id: 4, colorIndex: 3, json: poseAnimation.hair1.black, zIndex: 0 },
        { id: 5, colorIndex: 3, json: poseAnimation.bangs1.black, zIndex: 3 },
      ]},
      hair2: { jsons: [ 
        { id: 0, colorIndex: 1, json: poseAnimation.hair2.blonde, zIndex: 0 },
        { id: 1, colorIndex: 1, json: poseAnimation.bangs2.blonde, zIndex: 3 },
        { id: 2, colorIndex: 2, json: poseAnimation.hair2.brown, zIndex: 0 },
        { id: 3, colorIndex: 2, json: poseAnimation.bangs2.brown, zIndex: 3 },
        { id: 4, colorIndex: 3, json: poseAnimation.hair2.black, zIndex: 0 },
        { id: 5, colorIndex: 3, json: poseAnimation.bangs2.black, zIndex: 3 },     
      ]},
      hair3: { jsons: [
        { id: 0, colorIndex: 1, json: poseAnimation.hair3.blonde, zIndex: 0 },
        { id: 1, colorIndex: 1, json: poseAnimation.bangs3.blonde, zIndex: 3 },
        { id: 2, colorIndex: 2, json: poseAnimation.hair3.brown, zIndex: 0 },
        { id: 3, colorIndex: 2, json: poseAnimation.bangs3.brown, zIndex: 3 },
        { id: 4, colorIndex: 3, json: poseAnimation.hair3.black, zIndex: 0 },
        { id: 5, colorIndex: 3, json: poseAnimation.bangs3.black, zIndex: 3 },
      ]},
      hair4: { jsons: [
        { id: 0, colorIndex: 1, json: poseAnimation.hair4.blonde, zIndex: 0 },
        { id: 1, colorIndex: 1, json: poseAnimation.bangs4.blonde, zIndex: 3 },
        { id: 2, colorIndex: 2, json: poseAnimation.hair4.brown, zIndex: 0 },
        { id: 3, colorIndex: 2, json: poseAnimation.bangs4.brown, zIndex: 3 },
        { id: 4, colorIndex: 3, json: poseAnimation.hair4.black, zIndex: 0 },
        { id: 5, colorIndex: 3, json: poseAnimation.bangs4.black, zIndex: 3 },
      ]},
      hair5: { jsons: [
        { id: 0, colorIndex: 1, json: poseAnimation.hair5.blonde, zIndex: 0 },
        { id: 1, colorIndex: 1, json: poseAnimation.bangs5.blonde, zIndex: 3 },
        { id: 2, colorIndex: 2, json: poseAnimation.hair5.brown, zIndex: 0 },
        { id: 3, colorIndex: 2, json: poseAnimation.bangs5.brown, zIndex: 3 },
        { id: 4, colorIndex: 3, json: poseAnimation.hair5.black, zIndex: 0 },
        { id: 5, colorIndex: 3, json: poseAnimation.bangs5.black, zIndex: 3 },
      ]},
      hair6: { jsons: [
        { id: 0, colorIndex: 1, json: poseAnimation.hair6.blonde, zIndex: 0 },
        { id: 1, colorIndex: 1, json: poseAnimation.bangs6.blonde, zIndex: 3 },
        { id: 2, colorIndex: 2, json: poseAnimation.hair6.brown, zIndex: 0 },
        { id: 3, colorIndex: 2, json: poseAnimation.bangs6.brown, zIndex: 3 },
        { id: 4, colorIndex: 3, json: poseAnimation.hair6.black, zIndex: 0 },
        { id: 5, colorIndex: 3, json: poseAnimation.bangs6.black, zIndex: 3 },
      ]},
      outfit1: { jsons: [
        { id: 0, json: poseAnimation.outfit1.bottom, zIndex: 3 },
        { id: 1, json: poseAnimation.outfit1.shoes, zIndex: 2 },
        { id: 2, json: poseAnimation.outfit1.tops, zIndex: 3 },
        { id: 3, json: poseAnimation.outfit1.hat, zIndex: 3 },
      ]},
      outfit2: { jsons: [
        { id: 0, json: poseAnimation.outfit2.bottom, zIndex: 3 },
        { id: 1, json: poseAnimation.outfit2.shoes, zIndex: 2 },
        { id: 2, json: poseAnimation.outfit2.tops, zIndex: 3 },
        { id: 3, json: poseAnimation.outfit2.hat, zIndex: 3 },
      ] },
      outfit3: { jsons: [
        { id: 0, json: poseAnimation.outfit3.bottom, zIndex: 3 },
        { id: 1, json: poseAnimation.outfit3.shoes, zIndex: 2 },
        { id: 2, json: poseAnimation.outfit3.tops, zIndex: 3 },
        { id: 3, json: poseAnimation.outfit3.hat, zIndex: 3 },
      ] },
      gender1: { jsons: [
        { id: 0, colorIndex: 1, json: poseAnimation.eyebrows4.blonde, zIndex: 2 },
        { id: 1, colorIndex: 2, json: poseAnimation.eyebrows4.brown, zIndex: 2 },
        { id: 2, colorIndex: 3, json: poseAnimation.eyebrows4.black, zIndex: 2 },
        { id: 3, json: poseAnimation.eyes.eyesNoLash, zIndex: 2 },

      ]},
      gender2: { jsons: [
        { id: 0, colorIndex: 1, json: poseAnimation.eyebrows2.blonde, zIndex: 2 },
        { id: 1, colorIndex: 2, json: poseAnimation.eyebrows2.brown, zIndex: 2 },
        { id: 2, colorIndex: 3, json: poseAnimation.eyebrows2.black, zIndex: 2 },
        { id: 3, json: poseAnimation.eyes.eyesLash, zIndex: 2 },

      ]},
      gender3: { jsons: [
        { id: 0, colorIndex: 1, json: poseAnimation.eyebrows1.blonde, zIndex: 2 },
        { id: 1, colorIndex: 2, json: poseAnimation.eyebrows1.brown, zIndex: 2 },
        { id: 2, colorIndex: 3, json: poseAnimation.eyebrows1.black, zIndex: 2 },
        { id: 3, json: poseAnimation.eyes.eyesLash, zIndex: 2 },

      ]},
    },
  },
  {
    id: 1,
    name: 'shrug',
    layers: {
      baseBody: { variations: [
        { id: "#F7D0B1", jsons: [
          { id: 0, json: shurgAnimation.makeup.H_F7D0B1, zIndex: 2},
          { id: 1, json: shurgAnimation.ears.H_F7D0B1, zIndex: 1 },
          { id: 2, json: shurgAnimation.mouth.H_F7D0B1, zIndex: 2},
          { id: 3, json: shurgAnimation.baseBody.H_F7D0B1, zIndex: 1},
        ]},
        { id: "#E9B58F", jsons: [
          { id: 0, json: shurgAnimation.makeup.H_E9B58F, zIndex: 2},
          { id: 1, json: shurgAnimation.ears.H_E9B58F, zIndex: 1 },
          { id: 2, json: shurgAnimation.mouth.H_E9B58F, zIndex: 2},
          { id: 3, json: shurgAnimation.baseBody.H_E9B58F, zIndex: 1},
        ]},
        { id: "#D19F7C", jsons: [
          { id: 0, json: shurgAnimation.makeup.H_D19F7C, zIndex: 2},
          { id: 1, json: shurgAnimation.ears.H_D19F7C, zIndex: 1 },
          { id: 2, json: shurgAnimation.mouth.H_D19F7C, zIndex: 2},
          { id: 3, json: shurgAnimation.baseBody.H_D19F7C, zIndex: 1},
        ]},
        { id: "#BB7751", jsons: [
          { id: 0, json: shurgAnimation.makeup.H_BB7751, zIndex: 2},
          { id: 1, json: shurgAnimation.ears.H_BB7751, zIndex: 1 },
          { id: 2, json: shurgAnimation.mouth.H_BB7751, zIndex: 2},
          { id: 3, json: shurgAnimation.baseBody.H_BB7751, zIndex: 1},
        ]},
        { id: "#A65F2C", jsons: [
          { id: 0, json: shurgAnimation.makeup.H_A65F2C, zIndex: 2},
          { id: 1, json: shurgAnimation.ears.H_A65F2C, zIndex: 1 },
          { id: 2, json: shurgAnimation.mouth.H_A65F2C, zIndex: 2},
          { id: 3, json: shurgAnimation.baseBody.H_A65F2C, zIndex: 1},
        ]},
        { id: "#3B1F1B", jsons: [
          { id: 0, json: shurgAnimation.makeup.H_3B1F1B, zIndex: 2},
          { id: 1, json: shurgAnimation.ears.H_3B1F1B, zIndex: 1},
          { id: 2, json: shurgAnimation.mouth.H_3B1F1B, zIndex: 2},
          { id: 3, json: shurgAnimation.baseBody.H_3B1F1B, zIndex: 1},
        ]},
      ]},
      hair1: { jsons: [ 
        { id: 0, colorIndex: 1, json: shurgAnimation.hair1.blonde, zIndex: 0 },
        { id: 1, colorIndex: 1, json: shurgAnimation.bangs1.blonde, zIndex: 3 },
        { id: 2, colorIndex: 2, json: shurgAnimation.hair1.brown, zIndex: 0 },
        { id: 3, colorIndex: 2, json: shurgAnimation.bangs1.brown, zIndex: 3 },
        { id: 4, colorIndex: 3, json: shurgAnimation.hair1.black, zIndex: 0 },
        { id: 5, colorIndex: 3, json: shurgAnimation.bangs1.black, zIndex: 3 },
      ]},
      hair2: { jsons: [ 
        { id: 0, colorIndex: 1, json: shurgAnimation.hair2.blonde, zIndex: 0 },
        { id: 1, colorIndex: 1, json: shurgAnimation.bangs2.blonde, zIndex: 3 },
        { id: 2, colorIndex: 2, json: shurgAnimation.hair2.brown, zIndex: 0 },
        { id: 3, colorIndex: 2, json: shurgAnimation.bangs2.brown, zIndex: 3 },
        { id: 4, colorIndex: 3, json: shurgAnimation.hair2.black, zIndex: 0 },
        { id: 5, colorIndex: 3, json: shurgAnimation.bangs2.black, zIndex: 3 },     
      ]},
      hair3: { jsons: [
        { id: 0, colorIndex: 1, json: shurgAnimation.hair3.blonde, zIndex: 0 },
        { id: 1, colorIndex: 1, json: shurgAnimation.bangs3.blonde, zIndex: 3 },
        { id: 2, colorIndex: 2, json: shurgAnimation.hair3.brown, zIndex: 0 },
        { id: 3, colorIndex: 2, json: shurgAnimation.bangs3.brown, zIndex: 3 },
        { id: 4, colorIndex: 3, json: shurgAnimation.hair3.black, zIndex: 0 },
        { id: 5, colorIndex: 3, json: shurgAnimation.bangs3.black, zIndex: 3 },
      ]},
      hair4: { jsons: [
        { id: 0, colorIndex: 1, json: shurgAnimation.hair4.blonde, zIndex: 0 },
        { id: 1, colorIndex: 1, json: shurgAnimation.bangs4.blonde, zIndex: 3 },
        { id: 2, colorIndex: 2, json: shurgAnimation.hair4.brown, zIndex: 0 },
        { id: 3, colorIndex: 2, json: shurgAnimation.bangs4.brown, zIndex: 3 },
        { id: 4, colorIndex: 3, json: shurgAnimation.hair4.black, zIndex: 0 },
        { id: 5, colorIndex: 3, json: shurgAnimation.bangs4.black, zIndex: 3 },
      ]},
      hair5: { jsons: [
        { id: 0, colorIndex: 1, json: shurgAnimation.hair5.blonde, zIndex: 0 },
        { id: 1, colorIndex: 1, json: shurgAnimation.bangs5.blonde, zIndex: 3 },
        { id: 2, colorIndex: 2, json: shurgAnimation.hair5.brown, zIndex: 0 },
        { id: 3, colorIndex: 2, json: shurgAnimation.bangs5.brown, zIndex: 3 },
        { id: 4, colorIndex: 3, json: shurgAnimation.hair5.black, zIndex: 0 },
        { id: 5, colorIndex: 3, json: shurgAnimation.bangs5.black, zIndex: 3 },
      ]},
      hair6: { jsons: [
        { id: 0, colorIndex: 1, json: shurgAnimation.hair6.blonde, zIndex: 0 },
        { id: 1, colorIndex: 1, json: shurgAnimation.bangs6.blonde, zIndex: 3 },
        { id: 2, colorIndex: 2, json: shurgAnimation.hair6.brown, zIndex: 0 },
        { id: 3, colorIndex: 2, json: shurgAnimation.bangs6.brown, zIndex: 3 },
        { id: 4, colorIndex: 3, json: shurgAnimation.hair6.black, zIndex: 0 },
        { id: 5, colorIndex: 3, json: shurgAnimation.bangs6.black, zIndex: 3 },
      ]},
      outfit1: { jsons: [
        { id: 0, json: shurgAnimation.outfit1.bottom, zIndex: 3 },
        { id: 1, json: shurgAnimation.outfit1.shoes, zIndex: 2 },
        { id: 2, json: shurgAnimation.outfit1.tops, zIndex: 3 },
        { id: 3, json: shurgAnimation.outfit1.hat, zIndex: 3 },
      ]},
      outfit2: { jsons: [
        { id: 0, json: shurgAnimation.outfit2.bottom, zIndex: 3 },
        { id: 1, json: shurgAnimation.outfit2.shoes, zIndex: 2 },
        { id: 2, json: shurgAnimation.outfit2.tops, zIndex: 3 },
        { id: 3, json: shurgAnimation.outfit2.hat, zIndex: 3 },
      ] },
      outfit3: { jsons: [
        { id: 0, json: shurgAnimation.outfit3.bottom, zIndex: 3 },
        { id: 1, json: shurgAnimation.outfit3.shoes, zIndex: 2 },
        { id: 2, json: shurgAnimation.outfit3.tops, zIndex: 3 },
        { id: 3, json: shurgAnimation.outfit3.hat, zIndex: 3 },
      ] },
      gender1: { jsons: [
        { id: 0, colorIndex: 1, json: shurgAnimation.eyebrows4.blonde, zIndex: 2 },
        { id: 1, colorIndex: 2, json: shurgAnimation.eyebrows4.brown, zIndex: 2 },
        { id: 2, colorIndex: 3, json: shurgAnimation.eyebrows4.black, zIndex: 2 },
        { id: 3, json: shurgAnimation.eyes.eyesNoLash, zIndex: 2 },

      ]},
      gender2: { jsons: [
        { id: 0, colorIndex: 1, json: shurgAnimation.eyebrows2.blonde, zIndex: 2 },
        { id: 1, colorIndex: 2, json: shurgAnimation.eyebrows2.brown, zIndex: 2 },
        { id: 2, colorIndex: 3, json: shurgAnimation.eyebrows2.black, zIndex: 2 },
        { id: 3, json: shurgAnimation.eyes.eyesLash, zIndex: 2 },

      ]},
      gender3: { jsons: [
        { id: 0, colorIndex: 1, json: shurgAnimation.eyebrows1.blonde, zIndex: 2 },
        { id: 1, colorIndex: 2, json: shurgAnimation.eyebrows1.brown, zIndex: 2 },
        { id: 2, colorIndex: 3, json: shurgAnimation.eyebrows1.black, zIndex: 2 },
        { id: 3, json: shurgAnimation.eyes.eyesLash, zIndex: 2 },

      ]},
    },
  },
  {
    id: 2,
    name: 'flyingUp',
    layers: {
      baseBody: { variations: [
        { id: "#F7D0B1", jsons: [
          { id: 0, json: flyingUpAnimation.makeup.H_F7D0B1, zIndex: 2},
          { id: 1, json: flyingUpAnimation.ears.H_F7D0B1, zIndex: 1 },
          { id: 2, json: flyingUpAnimation.mouth.H_F7D0B1, zIndex: 2},
          { id: 3, json: flyingUpAnimation.baseBody.H_F7D0B1, zIndex: 1},
        ]},
        { id: "#E9B58F", jsons: [
          { id: 0, json: flyingUpAnimation.makeup.H_E9B58F, zIndex: 2},
          { id: 1, json: flyingUpAnimation.ears.H_E9B58F, zIndex: 1 },
          { id: 2, json: flyingUpAnimation.mouth.H_E9B58F, zIndex: 2},
          { id: 3, json: flyingUpAnimation.baseBody.H_E9B58F, zIndex: 1},
        ]},
        { id: "#D19F7C", jsons: [
          { id: 0, json: flyingUpAnimation.makeup.H_D19F7C, zIndex: 2},
          { id: 1, json: flyingUpAnimation.ears.H_D19F7C, zIndex: 1 },
          { id: 2, json: flyingUpAnimation.mouth.H_D19F7C, zIndex: 2},
          { id: 3, json: flyingUpAnimation.baseBody.H_D19F7C, zIndex: 1},
        ]},
        { id: "#BB7751", jsons: [
          { id: 0, json: flyingUpAnimation.makeup.H_BB7751, zIndex: 2},
          { id: 1, json: flyingUpAnimation.ears.H_BB7751, zIndex: 1 },
          { id: 2, json: flyingUpAnimation.mouth.H_BB7751, zIndex: 2},
          { id: 3, json: flyingUpAnimation.baseBody.H_BB7751, zIndex: 1},
        ]},
        { id: "#A65F2C", jsons: [
          { id: 0, json: flyingUpAnimation.makeup.H_A65F2C, zIndex: 2},
          { id: 1, json: flyingUpAnimation.ears.H_A65F2C, zIndex: 1 },
          { id: 2, json: flyingUpAnimation.mouth.H_A65F2C, zIndex: 2},
          { id: 3, json: flyingUpAnimation.baseBody.H_A65F2C, zIndex: 1},
        ]},
        { id: "#3B1F1B", jsons: [
          { id: 0, json: flyingUpAnimation.makeup.H_3B1F1B, zIndex: 2},
          { id: 1, json: flyingUpAnimation.ears.H_3B1F1B, zIndex: 1},
          { id: 2, json: flyingUpAnimation.mouth.H_3B1F1B, zIndex: 2},
          { id: 3, json: flyingUpAnimation.baseBody.H_3B1F1B, zIndex: 1},
        ]},
      ]},
      hair1: { jsons: [ 
        { id: 0, colorIndex: 1, json: flyingUpAnimation.hair1.blonde, zIndex: 0 },
        { id: 1, colorIndex: 1, json: flyingUpAnimation.bangs1.blonde, zIndex: 3 },
        { id: 2, colorIndex: 2, json: flyingUpAnimation.hair1.brown, zIndex: 0 },
        { id: 3, colorIndex: 2, json: flyingUpAnimation.bangs1.brown, zIndex: 3 },
        { id: 4, colorIndex: 3, json: flyingUpAnimation.hair1.black, zIndex: 0 },
        { id: 5, colorIndex: 3, json: flyingUpAnimation.bangs1.black, zIndex: 3 },
      ]},
      hair2: { jsons: [ 
        { id: 0, colorIndex: 1, json: flyingUpAnimation.hair2.blonde, zIndex: 0 },
        { id: 1, colorIndex: 1, json: flyingUpAnimation.bangs2.blonde, zIndex: 3 },
        { id: 2, colorIndex: 2, json: flyingUpAnimation.hair2.brown, zIndex: 0 },
        { id: 3, colorIndex: 2, json: flyingUpAnimation.bangs2.brown, zIndex: 3 },
        { id: 4, colorIndex: 3, json: flyingUpAnimation.hair2.black, zIndex: 0 },
        { id: 5, colorIndex: 3, json: flyingUpAnimation.bangs2.black, zIndex: 3 },     
      ]},
      hair3: { jsons: [
        { id: 0, colorIndex: 1, json: flyingUpAnimation.hair3.blonde, zIndex: 0 },
        { id: 1, colorIndex: 1, json: flyingUpAnimation.bangs3.blonde, zIndex: 3 },
        { id: 2, colorIndex: 2, json: flyingUpAnimation.hair3.brown, zIndex: 0 },
        { id: 3, colorIndex: 2, json: flyingUpAnimation.bangs3.brown, zIndex: 3 },
        { id: 4, colorIndex: 3, json: flyingUpAnimation.hair3.black, zIndex: 0 },
        { id: 5, colorIndex: 3, json: flyingUpAnimation.bangs3.black, zIndex: 3 },
      ]},
      hair4: { jsons: [
        { id: 0, colorIndex: 1, json: flyingUpAnimation.hair4.blonde, zIndex: 0 },
        { id: 1, colorIndex: 1, json: flyingUpAnimation.bangs4.blonde, zIndex: 3 },
        { id: 2, colorIndex: 2, json: flyingUpAnimation.hair4.brown, zIndex: 0 },
        { id: 3, colorIndex: 2, json: flyingUpAnimation.bangs4.brown, zIndex: 3 },
        { id: 4, colorIndex: 3, json: flyingUpAnimation.hair4.black, zIndex: 0 },
        { id: 5, colorIndex: 3, json: flyingUpAnimation.bangs4.black, zIndex: 3 },
      ]},
      hair5: { jsons: [
        { id: 0, colorIndex: 1, json: flyingUpAnimation.hair5.blonde, zIndex: 0 },
        { id: 1, colorIndex: 1, json: flyingUpAnimation.bangs5.blonde, zIndex: 3 },
        { id: 2, colorIndex: 2, json: flyingUpAnimation.hair5.brown, zIndex: 0 },
        { id: 3, colorIndex: 2, json: flyingUpAnimation.bangs5.brown, zIndex: 3 },
        { id: 4, colorIndex: 3, json: flyingUpAnimation.hair5.black, zIndex: 0 },
        { id: 5, colorIndex: 3, json: flyingUpAnimation.bangs5.black, zIndex: 3 },
      ]},
      hair6: { jsons: [
        { id: 0, colorIndex: 1, json: flyingUpAnimation.hair6.blonde, zIndex: 0 },
        { id: 1, colorIndex: 1, json: flyingUpAnimation.bangs6.blonde, zIndex: 3 },
        { id: 2, colorIndex: 2, json: flyingUpAnimation.hair6.brown, zIndex: 0 },
        { id: 3, colorIndex: 2, json: flyingUpAnimation.bangs6.brown, zIndex: 3 },
        { id: 4, colorIndex: 3, json: flyingUpAnimation.hair6.black, zIndex: 0 },
        { id: 5, colorIndex: 3, json: flyingUpAnimation.bangs6.black, zIndex: 3 },
      ]},
      outfit1: { jsons: [
        { id: 0, json: flyingUpAnimation.outfit1.bottom, zIndex: 3 },
        { id: 1, json: flyingUpAnimation.outfit1.shoes, zIndex: 2 },
        { id: 2, json: flyingUpAnimation.outfit1.tops, zIndex: 3 },
        { id: 3, json: flyingUpAnimation.outfit1.hat1, zIndex: 3 },
        { id: 4, json: flyingUpAnimation.outfit1.hat2, zIndex: 2 },
      ]},
      outfit2: { jsons: [
        { id: 0, json: flyingUpAnimation.outfit2.bottom, zIndex: 3 },
        { id: 1, json: flyingUpAnimation.outfit2.shoes, zIndex: 2 },
        { id: 2, json: flyingUpAnimation.outfit2.tops, zIndex: 3 },
        { id: 3, json: flyingUpAnimation.outfit2.hat, zIndex: 3 },
      ] },
      outfit3: { jsons: [
        { id: 0, json: flyingUpAnimation.outfit3.bottom, zIndex: 3 },
        { id: 1, json: flyingUpAnimation.outfit3.shoes, zIndex: 2 },
        { id: 2, json: flyingUpAnimation.outfit3.tops, zIndex: 3 },
        { id: 3, json: flyingUpAnimation.outfit3.hat, zIndex: 3 },
      ] },
      gender1: { jsons: [
        { id: 0, colorIndex: 1, json: flyingUpAnimation.eyebrows4.blonde, zIndex: 2 },
        { id: 1, colorIndex: 2, json: flyingUpAnimation.eyebrows4.brown, zIndex: 2 },
        { id: 2, colorIndex: 3, json: flyingUpAnimation.eyebrows4.black, zIndex: 2 },
        { id: 3, json: flyingUpAnimation.eyes.eyesNoLash, zIndex: 2 },
      ]},
      gender2: { jsons: [
        { id: 0, colorIndex: 1, json: flyingUpAnimation.eyebrows2.blonde, zIndex: 2 },
        { id: 1, colorIndex: 2, json: flyingUpAnimation.eyebrows2.brown, zIndex: 2 },
        { id: 2, colorIndex: 3, json: flyingUpAnimation.eyebrows2.black, zIndex: 2 },
        { id: 3, json: flyingUpAnimation.eyes.eyesLash, zIndex: 2 },

      ]},
      gender3: { jsons: [
        { id: 0, colorIndex: 1, json: flyingUpAnimation.eyebrows1.blonde, zIndex: 2 },
        { id: 1, colorIndex: 2, json: flyingUpAnimation.eyebrows1.brown, zIndex: 2 },
        { id: 2, colorIndex: 3, json: flyingUpAnimation.eyebrows1.black, zIndex: 2 },
        { id: 3, json: flyingUpAnimation.eyes.eyesLash, zIndex: 2 },
      ]},
    },
  },
  {
    id: 3,
    name: 'flyingSide',
    layers: {
      baseBody: { variations: [
        { id: "#F7D0B1", jsons: [
          { id: 0, json: flyingSideAnimation.makeup.H_F7D0B1, zIndex: 2},
          { id: 1, json: flyingSideAnimation.ears.H_F7D0B1, zIndex: 1 },
          { id: 2, json: flyingSideAnimation.mouth.H_F7D0B1, zIndex: 2},
          { id: 3, json: flyingSideAnimation.baseBody.H_F7D0B1, zIndex: 1},
        ]},
        { id: "#E9B58F", jsons: [
          { id: 0, json: flyingSideAnimation.makeup.H_E9B58F, zIndex: 2},
          { id: 1, json: flyingSideAnimation.ears.H_E9B58F, zIndex: 1 },
          { id: 2, json: flyingSideAnimation.mouth.H_E9B58F, zIndex: 2},
          { id: 3, json: flyingSideAnimation.baseBody.H_E9B58F, zIndex: 1},
        ]},
        { id: "#D19F7C", jsons: [
          { id: 0, json: flyingSideAnimation.makeup.H_D19F7C, zIndex: 2},
          { id: 1, json: flyingSideAnimation.ears.H_D19F7C, zIndex: 1 },
          { id: 2, json: flyingSideAnimation.mouth.H_D19F7C, zIndex: 2},
          { id: 3, json: flyingSideAnimation.baseBody.H_D19F7C, zIndex: 1},
        ]},
        { id: "#BB7751", jsons: [
          { id: 0, json: flyingSideAnimation.makeup.H_BB7751, zIndex: 2},
          { id: 1, json: flyingSideAnimation.ears.H_BB7751, zIndex: 1 },
          { id: 2, json: flyingSideAnimation.mouth.H_BB7751, zIndex: 2},
          { id: 3, json: flyingSideAnimation.baseBody.H_BB7751, zIndex: 1},
        ]},
        { id: "#A65F2C", jsons: [
          { id: 0, json: flyingSideAnimation.makeup.H_A65F2C, zIndex: 2},
          { id: 1, json: flyingSideAnimation.ears.H_A65F2C, zIndex: 1 },
          { id: 2, json: flyingSideAnimation.mouth.H_A65F2C, zIndex: 2},
          { id: 3, json: flyingSideAnimation.baseBody.H_A65F2C, zIndex: 1},
        ]},
        { id: "#3B1F1B", jsons: [
          { id: 0, json: flyingSideAnimation.makeup.H_3B1F1B, zIndex: 2},
          { id: 1, json: flyingSideAnimation.ears.H_3B1F1B, zIndex: 1},
          { id: 2, json: flyingSideAnimation.mouth.H_3B1F1B, zIndex: 2},
          { id: 3, json: flyingSideAnimation.baseBody.H_3B1F1B, zIndex: 1},
        ]},
      ]},
      hair1: { jsons: [ 
        { id: 0, colorIndex: 1, json: flyingSideAnimation.hair1.blonde, zIndex: 0 },
        { id: 1, colorIndex: 1, json: flyingSideAnimation.bangs1.blonde, zIndex: 3 },
        { id: 2, colorIndex: 2, json: flyingSideAnimation.hair1.brown, zIndex: 0 },
        { id: 3, colorIndex: 2, json: flyingSideAnimation.bangs1.brown, zIndex: 3 },
        { id: 4, colorIndex: 3, json: flyingSideAnimation.hair1.black, zIndex: 0 },
        { id: 5, colorIndex: 3, json: flyingSideAnimation.bangs1.black, zIndex: 3 },
      ]},
      hair2: { jsons: [ 
        { id: 0, colorIndex: 1, json: flyingSideAnimation.hair2.blonde, zIndex: 0 },
        { id: 1, colorIndex: 1, json: flyingSideAnimation.bangs2.blonde, zIndex: 3 },
        { id: 2, colorIndex: 2, json: flyingSideAnimation.hair2.brown, zIndex: 0 },
        { id: 3, colorIndex: 2, json: flyingSideAnimation.bangs2.brown, zIndex: 3 },
        { id: 4, colorIndex: 3, json: flyingSideAnimation.hair2.black, zIndex: 0 },
        { id: 5, colorIndex: 3, json: flyingSideAnimation.bangs2.black, zIndex: 3 },     
      ]},
      hair3: { jsons: [
        { id: 0, colorIndex: 1, json: flyingSideAnimation.hair3.blonde, zIndex: 0 },
        { id: 1, colorIndex: 1, json: flyingSideAnimation.bangs3.blonde, zIndex: 3 },
        { id: 2, colorIndex: 2, json: flyingSideAnimation.hair3.brown, zIndex: 0 },
        { id: 3, colorIndex: 2, json: flyingSideAnimation.bangs3.brown, zIndex: 3 },
        { id: 4, colorIndex: 3, json: flyingSideAnimation.hair3.black, zIndex: 0 },
        { id: 5, colorIndex: 3, json: flyingSideAnimation.bangs3.black, zIndex: 3 },
      ]},
      hair4: { jsons: [
        { id: 0, colorIndex: 1, json: flyingSideAnimation.hair4.blonde, zIndex: 0 },
        { id: 1, colorIndex: 1, json: flyingSideAnimation.bangs4.blonde, zIndex: 3 },
        { id: 2, colorIndex: 2, json: flyingSideAnimation.hair4.brown, zIndex: 0 },
        { id: 3, colorIndex: 2, json: flyingSideAnimation.bangs4.brown, zIndex: 3 },
        { id: 4, colorIndex: 3, json: flyingSideAnimation.hair4.black, zIndex: 0 },
        { id: 5, colorIndex: 3, json: flyingSideAnimation.bangs4.black, zIndex: 3 },
      ]},
      hair5: { jsons: [
        { id: 0, colorIndex: 1, json: flyingSideAnimation.hair5.blonde, zIndex: 0 },
        { id: 1, colorIndex: 1, json: flyingSideAnimation.bangs5.blonde, zIndex: 3 },
        { id: 2, colorIndex: 2, json: flyingSideAnimation.hair5.brown, zIndex: 0 },
        { id: 3, colorIndex: 2, json: flyingSideAnimation.bangs5.brown, zIndex: 3 },
        { id: 4, colorIndex: 3, json: flyingSideAnimation.hair5.black, zIndex: 0 },
        { id: 5, colorIndex: 3, json: flyingSideAnimation.bangs5.black, zIndex: 3 },
      ]},
      hair6: { jsons: [
        { id: 0, colorIndex: 1, json: flyingSideAnimation.hair6.blonde, zIndex: 0 },
        { id: 1, colorIndex: 1, json: flyingSideAnimation.bangs6.blonde, zIndex: 3 },
        { id: 2, colorIndex: 2, json: flyingSideAnimation.hair6.brown, zIndex: 0 },
        { id: 3, colorIndex: 2, json: flyingSideAnimation.bangs6.brown, zIndex: 3 },
        { id: 4, colorIndex: 3, json: flyingSideAnimation.hair6.black, zIndex: 0 },
        { id: 5, colorIndex: 3, json: flyingSideAnimation.bangs6.black, zIndex: 3 },
      ]},
      outfit1: { jsons: [
        { id: 0, json: flyingSideAnimation.outfit1.bottom, zIndex: 3 },
        { id: 1, json: flyingSideAnimation.outfit1.shoes, zIndex: 2 },
        { id: 2, json: flyingSideAnimation.outfit1.tops, zIndex: 3 },
        { id: 3, json: flyingSideAnimation.outfit1.hat, zIndex: 3 },
      ]},
      outfit2: { jsons: [
        { id: 0, json: flyingSideAnimation.outfit2.bottom, zIndex: 3 },
        { id: 1, json: flyingSideAnimation.outfit2.shoes, zIndex: 2 },
        { id: 2, json: flyingSideAnimation.outfit2.tops, zIndex: 3 },
        { id: 3, json: flyingSideAnimation.outfit2.hat, zIndex: 3 },
      ] },
      outfit3: { jsons: [
        { id: 0, json: flyingSideAnimation.outfit3.bottom, zIndex: 3 },
        { id: 1, json: flyingSideAnimation.outfit3.shoes, zIndex: 2 },
        { id: 2, json: flyingSideAnimation.outfit3.tops, zIndex: 3 },
        { id: 3, json: flyingSideAnimation.outfit3.hat, zIndex: 3 },
      ] },
      gender1: { jsons: [
        { id: 0, colorIndex: 1, json: flyingSideAnimation.eyebrows4.blonde, zIndex: 2 },
        { id: 1, colorIndex: 2, json: flyingSideAnimation.eyebrows4.brown, zIndex: 2 },
        { id: 2, colorIndex: 3, json: flyingSideAnimation.eyebrows4.black, zIndex: 2 },
        { id: 3, json: flyingSideAnimation.eyes.eyesNoLash, zIndex: 2 },

      ]},
      gender2: { jsons: [
        { id: 0, colorIndex: 1, json: flyingSideAnimation.eyebrows2.blonde, zIndex: 2 },
        { id: 1, colorIndex: 2, json: flyingSideAnimation.eyebrows2.brown, zIndex: 2 },
        { id: 2, colorIndex: 3, json: flyingSideAnimation.eyebrows2.black, zIndex: 2 },
        { id: 3, json: flyingSideAnimation.eyes.eyesLash, zIndex: 2 },

      ]},
      gender3: { jsons: [
        { id: 0, colorIndex: 1, json: flyingSideAnimation.eyebrows1.blonde, zIndex: 2 },
        { id: 1, colorIndex: 2, json: flyingSideAnimation.eyebrows1.brown, zIndex: 2 },
        { id: 2, colorIndex: 3, json: flyingSideAnimation.eyebrows1.black, zIndex: 2 },
        { id: 3, json: flyingSideAnimation.eyes.eyesLash, zIndex: 2 },

      ]},
    },
  },
  {
    id: 4,
    name: 'thumbsUp',
    layers: {
      baseBody: { variations: [
        { id: "#F7D0B1", jsons: [
          { id: 0, json: thumbsUpAnimation.makeup.H_F7D0B1, zIndex: 2},
          { id: 1, json: thumbsUpAnimation.ears.H_F7D0B1, zIndex: 1 },
          { id: 2, json: thumbsUpAnimation.mouth.H_F7D0B1, zIndex: 2},
          { id: 3, json: thumbsUpAnimation.baseBody.H_F7D0B1, zIndex: 1},
        ]},
        { id: "#E9B58F", jsons: [
          { id: 0, json: thumbsUpAnimation.makeup.H_E9B58F, zIndex: 2},
          { id: 1, json: thumbsUpAnimation.ears.H_E9B58F, zIndex: 1 },
          { id: 2, json: thumbsUpAnimation.mouth.H_E9B58F, zIndex: 2},
          { id: 3, json: thumbsUpAnimation.baseBody.H_E9B58F, zIndex: 1},
        ]},
        { id: "#D19F7C", jsons: [
          { id: 0, json: thumbsUpAnimation.makeup.H_D19F7C, zIndex: 2},
          { id: 1, json: thumbsUpAnimation.ears.H_D19F7C, zIndex: 1 },
          { id: 2, json: thumbsUpAnimation.mouth.H_D19F7C, zIndex: 2},
          { id: 3, json: thumbsUpAnimation.baseBody.H_D19F7C, zIndex: 1},
        ]},
        { id: "#BB7751", jsons: [
          { id: 0, json: thumbsUpAnimation.makeup.H_BB7751, zIndex: 2},
          { id: 1, json: thumbsUpAnimation.ears.H_BB7751, zIndex: 1 },
          { id: 2, json: thumbsUpAnimation.mouth.H_BB7751, zIndex: 2},
          { id: 3, json: thumbsUpAnimation.baseBody.H_BB7751, zIndex: 1},
        ]},
        { id: "#A65F2C", jsons: [
          { id: 0, json: thumbsUpAnimation.makeup.H_A65F2C, zIndex: 2},
          { id: 1, json: thumbsUpAnimation.ears.H_A65F2C, zIndex: 1 },
          { id: 2, json: thumbsUpAnimation.mouth.H_A65F2C, zIndex: 2},
          { id: 3, json: thumbsUpAnimation.baseBody.H_A65F2C, zIndex: 1},
        ]},
        { id: "#3B1F1B", jsons: [
          { id: 0, json: thumbsUpAnimation.makeup.H_3B1F1B, zIndex: 2},
          { id: 1, json: thumbsUpAnimation.ears.H_3B1F1B, zIndex: 1},
          { id: 2, json: thumbsUpAnimation.mouth.H_3B1F1B, zIndex: 2},
          { id: 3, json: thumbsUpAnimation.baseBody.H_3B1F1B, zIndex: 1},
        ]},
      ]},
      hair1: { jsons: [ 
        { id: 0, colorIndex: 1, json: thumbsUpAnimation.hair1.blonde, zIndex: 0 },
        { id: 1, colorIndex: 1, json: thumbsUpAnimation.bangs1.blonde, zIndex: 3 },
        { id: 2, colorIndex: 2, json: thumbsUpAnimation.hair1.brown, zIndex: 0 },
        { id: 3, colorIndex: 2, json: thumbsUpAnimation.bangs1.brown, zIndex: 3 },
        { id: 4, colorIndex: 3, json: thumbsUpAnimation.hair1.black, zIndex: 0 },
        { id: 5, colorIndex: 3, json: thumbsUpAnimation.bangs1.black, zIndex: 3 },
      ]},
      hair2: { jsons: [ 
        { id: 0, colorIndex: 1, json: thumbsUpAnimation.hair2.blonde, zIndex: 0 },
        { id: 1, colorIndex: 1, json: thumbsUpAnimation.bangs2.blonde, zIndex: 3 },
        { id: 2, colorIndex: 2, json: thumbsUpAnimation.hair2.brown, zIndex: 0 },
        { id: 3, colorIndex: 2, json: thumbsUpAnimation.bangs2.brown, zIndex: 3 },
        { id: 4, colorIndex: 3, json: thumbsUpAnimation.hair2.black, zIndex: 0 },
        { id: 5, colorIndex: 3, json: thumbsUpAnimation.bangs2.black, zIndex: 3 },     
      ]},
      hair3: { jsons: [
        { id: 0, colorIndex: 1, json: thumbsUpAnimation.hair3.blonde, zIndex: 0 },
        { id: 1, colorIndex: 1, json: thumbsUpAnimation.bangs3.blonde, zIndex: 3 },
        { id: 2, colorIndex: 2, json: thumbsUpAnimation.hair3.brown, zIndex: 0 },
        { id: 3, colorIndex: 2, json: thumbsUpAnimation.bangs3.brown, zIndex: 3 },
        { id: 4, colorIndex: 3, json: thumbsUpAnimation.hair3.black, zIndex: 0 },
        { id: 5, colorIndex: 3, json: thumbsUpAnimation.bangs3.black, zIndex: 3 },
      ]},
      hair4: { jsons: [
        { id: 0, colorIndex: 1, json: thumbsUpAnimation.hair4.blonde, zIndex: 0 },
        { id: 1, colorIndex: 1, json: thumbsUpAnimation.bangs4.blonde, zIndex: 3 },
        { id: 2, colorIndex: 2, json: thumbsUpAnimation.hair4.brown, zIndex: 0 },
        { id: 3, colorIndex: 2, json: thumbsUpAnimation.bangs4.brown, zIndex: 3 },
        { id: 4, colorIndex: 3, json: thumbsUpAnimation.hair4.black, zIndex: 0 },
        { id: 5, colorIndex: 3, json: thumbsUpAnimation.bangs4.black, zIndex: 3 },
      ]},
      hair5: { jsons: [
        { id: 0, colorIndex: 1, json: thumbsUpAnimation.hair5.blonde, zIndex: 0 },
        { id: 1, colorIndex: 1, json: thumbsUpAnimation.bangs5.blonde, zIndex: 3 },
        { id: 2, colorIndex: 2, json: thumbsUpAnimation.hair5.brown, zIndex: 0 },
        { id: 3, colorIndex: 2, json: thumbsUpAnimation.bangs5.brown, zIndex: 3 },
        { id: 4, colorIndex: 3, json: thumbsUpAnimation.hair5.black, zIndex: 0 },
        { id: 5, colorIndex: 3, json: thumbsUpAnimation.bangs5.black, zIndex: 3 },
      ]},
      hair6: { jsons: [
        { id: 0, colorIndex: 1, json: thumbsUpAnimation.hair6.blonde, zIndex: 0 },
        { id: 1, colorIndex: 1, json: thumbsUpAnimation.bangs6.blonde, zIndex: 3 },
        { id: 2, colorIndex: 2, json: thumbsUpAnimation.hair6.brown, zIndex: 0 },
        { id: 3, colorIndex: 2, json: thumbsUpAnimation.bangs6.brown, zIndex: 3 },
        { id: 4, colorIndex: 3, json: thumbsUpAnimation.hair6.black, zIndex: 0 },
        { id: 5, colorIndex: 3, json: thumbsUpAnimation.bangs6.black, zIndex: 3 },
      ]},
      outfit1: { jsons: [
        { id: 0, json: thumbsUpAnimation.outfit1.bottom, zIndex: 3 },
        { id: 1, json: thumbsUpAnimation.outfit1.shoes, zIndex: 2 },
        { id: 2, json: thumbsUpAnimation.outfit1.tops, zIndex: 3 },
        { id: 3, json: thumbsUpAnimation.outfit1.hat1, zIndex: 3 },
        { id: 4, json: thumbsUpAnimation.outfit1.hat2, zIndex: 2 },
      ]},
      outfit2: { jsons: [
        { id: 0, json: thumbsUpAnimation.outfit2.bottom, zIndex: 3 },
        { id: 1, json: thumbsUpAnimation.outfit2.shoes, zIndex: 2 },
        { id: 2, json: thumbsUpAnimation.outfit2.tops, zIndex: 3 },
        { id: 3, json: thumbsUpAnimation.outfit2.hat, zIndex: 3 },
      ] },
      outfit3: { jsons: [
        { id: 0, json: thumbsUpAnimation.outfit3.bottom, zIndex: 3 },
        { id: 1, json: thumbsUpAnimation.outfit3.shoes, zIndex: 2 },
        { id: 2, json: thumbsUpAnimation.outfit3.tops, zIndex: 3 },
        { id: 3, json: thumbsUpAnimation.outfit3.hat, zIndex: 3 },
      ] },
      gender1: { jsons: [
        { id: 0, colorIndex: 1, json: thumbsUpAnimation.eyebrows4.blonde, zIndex: 2 },
        { id: 1, colorIndex: 2, json: thumbsUpAnimation.eyebrows4.brown, zIndex: 2 },
        { id: 2, colorIndex: 3, json: thumbsUpAnimation.eyebrows4.black, zIndex: 2 },
        { id: 3, json: thumbsUpAnimation.eyes.eyesNoLash, zIndex: 2 },

      ]},
      gender2: { jsons: [
        { id: 0, colorIndex: 1, json: thumbsUpAnimation.eyebrows2.blonde, zIndex: 2 },
        { id: 1, colorIndex: 2, json: thumbsUpAnimation.eyebrows2.brown, zIndex: 2 },
        { id: 2, colorIndex: 3, json: thumbsUpAnimation.eyebrows2.black, zIndex: 2 },
        { id: 3, json: thumbsUpAnimation.eyes.eyesLash, zIndex: 2 },

      ]},
      gender3: { jsons: [
        { id: 0, colorIndex: 1, json: thumbsUpAnimation.eyebrows1.blonde, zIndex: 2 },
        { id: 1, colorIndex: 2, json: thumbsUpAnimation.eyebrows1.brown, zIndex: 2 },
        { id: 2, colorIndex: 3, json: thumbsUpAnimation.eyebrows1.black, zIndex: 2 },
        { id: 3, json: thumbsUpAnimation.eyes.eyesLash, zIndex: 2 },

      ]},
    },
  },
  {
    id: 5,
    name: 'thumbsDown',
    layers: {
      baseBody: { variations: [
        { id: "#F7D0B1", jsons: [
          { id: 0, json: thumbsDownAnimation.makeup.H_F7D0B1, zIndex: 2},
          { id: 1, json: thumbsDownAnimation.ears.H_F7D0B1, zIndex: 1 },
          { id: 2, json: thumbsDownAnimation.mouth.H_F7D0B1, zIndex: 2},
          { id: 3, json: thumbsDownAnimation.baseBody.H_F7D0B1, zIndex: 1},
        ]},
        { id: "#E9B58F", jsons: [
          { id: 0, json: thumbsDownAnimation.makeup.H_E9B58F, zIndex: 2},
          { id: 1, json: thumbsDownAnimation.ears.H_E9B58F, zIndex: 1 },
          { id: 2, json: thumbsDownAnimation.mouth.H_E9B58F, zIndex: 2},
          { id: 3, json: thumbsDownAnimation.baseBody.H_E9B58F, zIndex: 1},
        ]},
        { id: "#D19F7C", jsons: [
          { id: 0, json: thumbsDownAnimation.makeup.H_D19F7C, zIndex: 2},
          { id: 1, json: thumbsDownAnimation.ears.H_D19F7C, zIndex: 1 },
          { id: 2, json: thumbsDownAnimation.mouth.H_D19F7C, zIndex: 2},
          { id: 3, json: thumbsDownAnimation.baseBody.H_D19F7C, zIndex: 1},
        ]},
        { id: "#BB7751", jsons: [
          { id: 0, json: thumbsDownAnimation.makeup.H_BB7751, zIndex: 2},
          { id: 1, json: thumbsDownAnimation.ears.H_BB7751, zIndex: 1 },
          { id: 2, json: thumbsDownAnimation.mouth.H_BB7751, zIndex: 2},
          { id: 3, json: thumbsDownAnimation.baseBody.H_BB7751, zIndex: 1},
        ]},
        { id: "#A65F2C", jsons: [
          { id: 0, json: thumbsDownAnimation.makeup.H_A65F2C, zIndex: 2},
          { id: 1, json: thumbsDownAnimation.ears.H_A65F2C, zIndex: 1 },
          { id: 2, json: thumbsDownAnimation.mouth.H_A65F2C, zIndex: 2},
          { id: 3, json: thumbsDownAnimation.baseBody.H_A65F2C, zIndex: 1},
        ]},
        { id: "#3B1F1B", jsons: [
          { id: 0, json: thumbsDownAnimation.makeup.H_3B1F1B, zIndex: 2},
          { id: 1, json: thumbsDownAnimation.ears.H_3B1F1B, zIndex: 1},
          { id: 2, json: thumbsDownAnimation.mouth.H_3B1F1B, zIndex: 2},
          { id: 3, json: thumbsDownAnimation.baseBody.H_3B1F1B, zIndex: 1},
        ]},
      ]},
      hair1: { jsons: [ 
        { id: 0, colorIndex: 1, json: thumbsDownAnimation.hair1.blonde, zIndex: 0 },
        { id: 1, colorIndex: 1, json: thumbsDownAnimation.bangs1.blonde, zIndex: 3 },
        { id: 2, colorIndex: 2, json: thumbsDownAnimation.hair1.brown, zIndex: 0 },
        { id: 3, colorIndex: 2, json: thumbsDownAnimation.bangs1.brown, zIndex: 3 },
        { id: 4, colorIndex: 3, json: thumbsDownAnimation.hair1.black, zIndex: 0 },
        { id: 5, colorIndex: 3, json: thumbsDownAnimation.bangs1.black, zIndex: 3 },
      ]},
      hair2: { jsons: [ 
        { id: 0, colorIndex: 1, json: thumbsDownAnimation.hair2.blonde, zIndex: 0 },
        { id: 1, colorIndex: 1, json: thumbsDownAnimation.bangs2.blonde, zIndex: 3 },
        { id: 2, colorIndex: 2, json: thumbsDownAnimation.hair2.brown, zIndex: 0 },
        { id: 3, colorIndex: 2, json: thumbsDownAnimation.bangs2.brown, zIndex: 3 },
        { id: 4, colorIndex: 3, json: thumbsDownAnimation.hair2.black, zIndex: 0 },
        { id: 5, colorIndex: 3, json: thumbsDownAnimation.bangs2.black, zIndex: 3 },     
      ]},
      hair3: { jsons: [
        { id: 0, colorIndex: 1, json: thumbsDownAnimation.hair3.blonde, zIndex: 0 },
        { id: 1, colorIndex: 1, json: thumbsDownAnimation.bangs3.blonde, zIndex: 3 },
        { id: 2, colorIndex: 2, json: thumbsDownAnimation.hair3.brown, zIndex: 0 },
        { id: 3, colorIndex: 2, json: thumbsDownAnimation.bangs3.brown, zIndex: 3 },
        { id: 4, colorIndex: 3, json: thumbsDownAnimation.hair3.black, zIndex: 0 },
        { id: 5, colorIndex: 3, json: thumbsDownAnimation.bangs3.black, zIndex: 3 },
      ]},
      hair4: { jsons: [
        { id: 0, colorIndex: 1, json: thumbsDownAnimation.hair4.blonde, zIndex: 0 },
        { id: 1, colorIndex: 1, json: thumbsDownAnimation.bangs4.blonde, zIndex: 3 },
        { id: 2, colorIndex: 2, json: thumbsDownAnimation.hair4.brown, zIndex: 0 },
        { id: 3, colorIndex: 2, json: thumbsDownAnimation.bangs4.brown, zIndex: 3 },
        { id: 4, colorIndex: 3, json: thumbsDownAnimation.hair4.black, zIndex: 0 },
        { id: 5, colorIndex: 3, json: thumbsDownAnimation.bangs4.black, zIndex: 3 },
      ]},
      hair5: { jsons: [
        { id: 0, colorIndex: 1, json: thumbsDownAnimation.hair5.blonde, zIndex: 0 },
        { id: 1, colorIndex: 1, json: thumbsDownAnimation.bangs5.blonde, zIndex: 3 },
        { id: 2, colorIndex: 2, json: thumbsDownAnimation.hair5.brown, zIndex: 0 },
        { id: 3, colorIndex: 2, json: thumbsDownAnimation.bangs5.brown, zIndex: 3 },
        { id: 4, colorIndex: 3, json: thumbsDownAnimation.hair5.black, zIndex: 0 },
        { id: 5, colorIndex: 3, json: thumbsDownAnimation.bangs5.black, zIndex: 3 },
      ]},
      hair6: { jsons: [
        { id: 0, colorIndex: 1, json: thumbsDownAnimation.hair6.blonde, zIndex: 0 },
        { id: 1, colorIndex: 1, json: thumbsDownAnimation.bangs6.blonde, zIndex: 3 },
        { id: 2, colorIndex: 2, json: thumbsDownAnimation.hair6.brown, zIndex: 0 },
        { id: 3, colorIndex: 2, json: thumbsDownAnimation.bangs6.brown, zIndex: 3 },
        { id: 4, colorIndex: 3, json: thumbsDownAnimation.hair6.black, zIndex: 0 },
        { id: 5, colorIndex: 3, json: thumbsDownAnimation.bangs6.black, zIndex: 3 },
      ]},
      outfit1: { jsons: [
        { id: 0, json: thumbsDownAnimation.outfit1.bottom, zIndex: 3 },
        { id: 1, json: thumbsDownAnimation.outfit1.shoes, zIndex: 2 },
        { id: 2, json: thumbsDownAnimation.outfit1.tops, zIndex: 3 },
        { id: 3, json: thumbsDownAnimation.outfit1.hat, zIndex: 3 },
      ]},
      outfit2: { jsons: [
        { id: 0, json: thumbsDownAnimation.outfit2.bottom, zIndex: 3 },
        { id: 1, json: thumbsDownAnimation.outfit2.shoes, zIndex: 2 },
        { id: 2, json: thumbsDownAnimation.outfit2.tops, zIndex: 3 },
        { id: 3, json: thumbsDownAnimation.outfit2.hat, zIndex: 3 },
      ] },
      outfit3: { jsons: [
        { id: 0, json: thumbsDownAnimation.outfit3.bottom, zIndex: 3 },
        { id: 1, json: thumbsDownAnimation.outfit3.shoes, zIndex: 2 },
        { id: 2, json: thumbsDownAnimation.outfit3.tops, zIndex: 3 },
        { id: 3, json: thumbsDownAnimation.outfit3.hat, zIndex: 3 },
      ] },
      gender1: { jsons: [
        { id: 0, colorIndex: 1, json: thumbsDownAnimation.eyebrows4.blonde, zIndex: 2 },
        { id: 1, colorIndex: 2, json: thumbsDownAnimation.eyebrows4.brown, zIndex: 2 },
        { id: 2, colorIndex: 3, json: thumbsDownAnimation.eyebrows4.black, zIndex: 2 },
        { id: 3, json: thumbsDownAnimation.eyes.eyesNoLash, zIndex: 2 },

      ]},
      gender2: { jsons: [
        { id: 0, colorIndex: 1, json: thumbsDownAnimation.eyebrows2.blonde, zIndex: 2 },
        { id: 1, colorIndex: 2, json: thumbsDownAnimation.eyebrows2.brown, zIndex: 2 },
        { id: 2, colorIndex: 3, json: thumbsDownAnimation.eyebrows2.black, zIndex: 2 },
        { id: 3, json: thumbsDownAnimation.eyes.eyesLash, zIndex: 2 },

      ]},
      gender3: { jsons: [
        { id: 0, colorIndex: 1, json: thumbsDownAnimation.eyebrows1.blonde, zIndex: 2 },
        { id: 1, colorIndex: 2, json: thumbsDownAnimation.eyebrows1.brown, zIndex: 2 },
        { id: 2, colorIndex: 3, json: thumbsDownAnimation.eyebrows1.black, zIndex: 2 },
        { id: 3, json: thumbsDownAnimation.eyes.eyesLash, zIndex: 2 },

      ]},
    },
  },
  {
    id: 6,
    name: 'touchdown',
    layers: {
      baseBody: { variations: [
        { id: "#F7D0B1", jsons: [
          { id: 0, json: touchdownAnimation.makeup.H_F7D0B1, zIndex: 2},
          { id: 1, json: touchdownAnimation.ears.H_F7D0B1, zIndex: 1 },
          { id: 2, json: touchdownAnimation.mouth.H_F7D0B1, zIndex: 2},
          { id: 3, json: touchdownAnimation.baseBody.H_F7D0B1, zIndex: 1},
        ]},
        { id: "#E9B58F", jsons: [
          { id: 0, json: touchdownAnimation.makeup.H_E9B58F, zIndex: 2},
          { id: 1, json: touchdownAnimation.ears.H_E9B58F, zIndex: 1 },
          { id: 2, json: touchdownAnimation.mouth.H_E9B58F, zIndex: 2},
          { id: 3, json: touchdownAnimation.baseBody.H_E9B58F, zIndex: 1},
        ]},
        { id: "#D19F7C", jsons: [
          { id: 0, json: touchdownAnimation.makeup.H_D19F7C, zIndex: 2},
          { id: 1, json: touchdownAnimation.ears.H_D19F7C, zIndex: 1 },
          { id: 2, json: touchdownAnimation.mouth.H_D19F7C, zIndex: 2},
          { id: 3, json: touchdownAnimation.baseBody.H_D19F7C, zIndex: 1},
        ]},
        { id: "#BB7751", jsons: [
          { id: 0, json: touchdownAnimation.makeup.H_BB7751, zIndex: 2},
          { id: 1, json: touchdownAnimation.ears.H_BB7751, zIndex: 1 },
          { id: 2, json: touchdownAnimation.mouth.H_BB7751, zIndex: 2},
          { id: 3, json: touchdownAnimation.baseBody.H_BB7751, zIndex: 1},
        ]},
        { id: "#A65F2C", jsons: [
          { id: 0, json: touchdownAnimation.makeup.H_A65F2C, zIndex: 2},
          { id: 1, json: touchdownAnimation.ears.H_A65F2C, zIndex: 1 },
          { id: 2, json: touchdownAnimation.mouth.H_A65F2C, zIndex: 2},
          { id: 3, json: touchdownAnimation.baseBody.H_A65F2C, zIndex: 1},
        ]},
        { id: "#3B1F1B", jsons: [
          { id: 0, json: touchdownAnimation.makeup.H_3B1F1B, zIndex: 2},
          { id: 1, json: touchdownAnimation.ears.H_3B1F1B, zIndex: 1},
          { id: 2, json: touchdownAnimation.mouth.H_3B1F1B, zIndex: 2},
          { id: 3, json: touchdownAnimation.baseBody.H_3B1F1B, zIndex: 1},
        ]},
      ]},
      hair1: { jsons: [ 
        { id: 0, colorIndex: 1, json: touchdownAnimation.hair1.blonde, zIndex: 0 },
        { id: 1, colorIndex: 1, json: touchdownAnimation.bangs1.blonde, zIndex: 3 },
        { id: 2, colorIndex: 2, json: touchdownAnimation.hair1.brown, zIndex: 0 },
        { id: 3, colorIndex: 2, json: touchdownAnimation.bangs1.brown, zIndex: 3 },
        { id: 4, colorIndex: 3, json: touchdownAnimation.hair1.black, zIndex: 0 },
        { id: 5, colorIndex: 3, json: touchdownAnimation.bangs1.black, zIndex: 3 },
      ]},
      hair2: { jsons: [ 
        { id: 0, colorIndex: 1, json: touchdownAnimation.hair2.blonde, zIndex: 0 },
        { id: 1, colorIndex: 1, json: touchdownAnimation.bangs2.blonde, zIndex: 3 },
        { id: 2, colorIndex: 2, json: touchdownAnimation.hair2.brown, zIndex: 0 },
        { id: 3, colorIndex: 2, json: touchdownAnimation.bangs2.brown, zIndex: 3 },
        { id: 4, colorIndex: 3, json: touchdownAnimation.hair2.black, zIndex: 0 },
        { id: 5, colorIndex: 3, json: touchdownAnimation.bangs2.black, zIndex: 3 },     
      ]},
      hair3: { jsons: [
        { id: 0, colorIndex: 1, json: touchdownAnimation.hair3.blonde, zIndex: 0 },
        { id: 1, colorIndex: 1, json: touchdownAnimation.bangs3.blonde, zIndex: 3 },
        { id: 2, colorIndex: 2, json: touchdownAnimation.hair3.brown, zIndex: 0 },
        { id: 3, colorIndex: 2, json: touchdownAnimation.bangs3.brown, zIndex: 3 },
        { id: 4, colorIndex: 3, json: touchdownAnimation.hair3.black, zIndex: 0 },
        { id: 5, colorIndex: 3, json: touchdownAnimation.bangs3.black, zIndex: 3 },
      ]},
      hair4: { jsons: [
        { id: 0, colorIndex: 1, json: touchdownAnimation.hair4.blonde, zIndex: 0 },
        { id: 1, colorIndex: 1, json: touchdownAnimation.bangs4.blonde, zIndex: 3 },
        { id: 2, colorIndex: 2, json: touchdownAnimation.hair4.brown, zIndex: 0 },
        { id: 3, colorIndex: 2, json: touchdownAnimation.bangs4.brown, zIndex: 3 },
        { id: 4, colorIndex: 3, json: touchdownAnimation.hair4.black, zIndex: 0 },
        { id: 5, colorIndex: 3, json: touchdownAnimation.bangs4.black, zIndex: 3 },
      ]},
      hair5: { jsons: [
        { id: 0, colorIndex: 1, json: touchdownAnimation.hair5.blonde, zIndex: 0 },
        { id: 1, colorIndex: 1, json: touchdownAnimation.bangs5.blonde, zIndex: 3 },
        { id: 2, colorIndex: 2, json: touchdownAnimation.hair5.brown, zIndex: 0 },
        { id: 3, colorIndex: 2, json: touchdownAnimation.bangs5.brown, zIndex: 3 },
        { id: 4, colorIndex: 3, json: touchdownAnimation.hair5.black, zIndex: 0 },
        { id: 5, colorIndex: 3, json: touchdownAnimation.bangs5.black, zIndex: 3 },
      ]},
      hair6: { jsons: [
        { id: 0, colorIndex: 1, json: touchdownAnimation.hair6.blonde, zIndex: 0 },
        { id: 1, colorIndex: 1, json: touchdownAnimation.bangs6.blonde, zIndex: 3 },
        { id: 2, colorIndex: 2, json: touchdownAnimation.hair6.brown, zIndex: 0 },
        { id: 3, colorIndex: 2, json: touchdownAnimation.bangs6.brown, zIndex: 3 },
        { id: 4, colorIndex: 3, json: touchdownAnimation.hair6.black, zIndex: 0 },
        { id: 5, colorIndex: 3, json: touchdownAnimation.bangs6.black, zIndex: 3 },
      ]},
      outfit1: { jsons: [
        { id: 0, json: touchdownAnimation.outfit1.bottom, zIndex: 3 },
        { id: 1, json: touchdownAnimation.outfit1.shoes, zIndex: 2 },
        { id: 2, json: touchdownAnimation.outfit1.tops, zIndex: 3 },
        { id: 3, json: touchdownAnimation.outfit1.hat, zIndex: 3 },
      ]},
      outfit2: { jsons: [
        { id: 0, json: touchdownAnimation.outfit2.bottom, zIndex: 3 },
        { id: 1, json: touchdownAnimation.outfit2.shoes, zIndex: 2 },
        { id: 2, json: touchdownAnimation.outfit2.tops, zIndex: 3 },
        { id: 3, json: touchdownAnimation.outfit2.hat, zIndex: 3 },
      ] },
      outfit3: { jsons: [
        { id: 0, json: touchdownAnimation.outfit3.bottom, zIndex: 3 },
        { id: 1, json: touchdownAnimation.outfit3.shoes, zIndex: 2 },
        { id: 2, json: touchdownAnimation.outfit3.tops, zIndex: 3 },
        { id: 3, json: touchdownAnimation.outfit3.hat, zIndex: 3 },
      ] },
      gender1: { jsons: [
        { id: 0, colorIndex: 1, json: touchdownAnimation.eyebrows4.blonde, zIndex: 2 },
        { id: 1, colorIndex: 2, json: touchdownAnimation.eyebrows4.brown, zIndex: 2 },
        { id: 2, colorIndex: 3, json: touchdownAnimation.eyebrows4.black, zIndex: 2 },
        { id: 3, json: touchdownAnimation.eyes.eyesNoLash, zIndex: 2 },

      ]},
      gender2: { jsons: [
        { id: 0, colorIndex: 1, json: touchdownAnimation.eyebrows2.blonde, zIndex: 2 },
        { id: 1, colorIndex: 2, json: touchdownAnimation.eyebrows2.brown, zIndex: 2 },
        { id: 2, colorIndex: 3, json: touchdownAnimation.eyebrows2.black, zIndex: 2 },
        { id: 3, json: touchdownAnimation.eyes.eyesLash, zIndex: 2 },

      ]},
      gender3: { jsons: [
        { id: 0, colorIndex: 1, json: touchdownAnimation.eyebrows1.blonde, zIndex: 2 },
        { id: 1, colorIndex: 2, json: touchdownAnimation.eyebrows1.brown, zIndex: 2 },
        { id: 2, colorIndex: 3, json: touchdownAnimation.eyebrows1.black, zIndex: 2 },
        { id: 3, json: touchdownAnimation.eyes.eyesLash, zIndex: 2 },

      ]},
    },
  },
]